---
- name: Add grafana apt key
  ansible.builtin.apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present
  become: yes

- name: Add grafana enterprise repo
  ansible.builtin.apt_repository:
    repo: deb https://packages.grafana.com/enterprise/deb stable main
    state: present
  become: yes

- name: Install grafana
  ansible.builtin.package:
    name: 
      - grafana-enterprise
    state: latest
    update_cache: yes
  become: yes

- name: Start grafana systemd service
  ansible.builtin.systemd:
    state: started
    daemon_reload: yes
    name: grafana-server
  become: yes

- name: Enable grafana systemd service
  ansible.builtin.systemd:
    name: grafana-server
    enabled: yes
  become: yes
