---
- name: Add Telegraf apt key
  ansible.builtin.apt_key:
    url: https://repos.influxdata.com/influxdb.key
    state: present
  become: yes

- name: Add Telegraf repo
  ansible.builtin.apt_repository:
    repo: deb https://repos.influxdata.com/ubuntu focal main
    state: present
  become: yes

- name: Install Telegraf
  ansible.builtin.package:
    name: 
      - telegraf
    state: latest
    update_cache: yes
  become: yes
