---
- name: Install essential packages
  ansible.builtin.package:
    name: "{{ ubuntu_packages }}"
    state: latest
  become: yes

- name: Install pip packages
  ansible.builtin.pip:
    name: "{{ pip_packages }}"

- name: Disable SSH password auth
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#PasswordAuthentication yes"
    line: "PasswordAuthentication no"
  register: sshd_config
  become: yes

- name: Change SSH port
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#Port 22"
    line: "Port {{ custom_ssh_port }}"
  register: sshd_config
  become: yes

- name: Enable passwordless sudo for "{{ username }}"
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    regexp: "^%wheel"
    line: "{{ username }} ALL=(ALL) NOPASSWD:ALL"
    validate: "/usr/sbin/visudo -cf %s"
  become: yes

- name: Restart SSH daemon
  ansible.builtin.service:
    name: sshd
    state: restarted
  when: sshd_config.changed
  become: yes
